### ISSUE TITLE
Best approach to change ports?

### ISSUE THREAD

**Issue by necromancyr** [calibrain/calibre-web-automated-book-downloader#12]
Wondering best approach to remap ports for both the main app and the cloudflare proxy?  Tried using the ENV variables, that didn't work (still used 8084 and 8000), tried remapping ports directly and that seemed to work but couldn't connect to the Cloudflare proxy w/localhost or got errors using an IP instead (connection refused).  

Guessing I'm just doing something incorrect, but would see shifting ports as a pretty big need for many.

**Comment by calibrain** [comment]
You are totally correct
I messed up my docker compose,
Its fixed now, see #13

**Comment by calibrain** [comment]
Sadly, cloudflarebypassforscraping port can't be changed, it's hardcoded from their service
But it shouldn't matter, since we are not exposing it
Its only used internally, and by hostname so you can have another service in your compose using the same port and it will work fine

Why are you trying to change the port ?

**Comment by necromancyr** [comment]
Thanks - you answered my question.  I was overthinking it and trying to remap more than I needed to.  Thanks!  This is addressed and working great!  (Now I just need a UI element in CWA to link to this! :))

**Comment by calibrain** [comment]
I am talking with the creator of CWA about that :P 
For now I have a hack where I apply inject the button in the HTML before spinning the CWA docker, I might clean it up a bit and share it next week
